pipeline{

agent any

stages{

stage('Checkout'){

steps{

git branch: "main", url: 'https://github.com/mdtauqeeralam21/g2-patient-health-records-service.git'

}

}

stage('Build'){

steps{

sh 'chmod a+x mvnw'

sh './mvnw clean package -DskipTests=true'

}

post{

always{

archiveArtifacts 'target/*.jar'

}

}

}

stage('DockerBuild') {

steps {

sh 'docker build -t services/g2-patient-health-records-service:latest .'

}

}

stage('Login') {

steps {

sh 'echo Tauqeer@786 | docker login -u tauqeeralam21 --password-stdin'

}

}

stage('Push') {

steps {

sh 'docker push services/g2-patient-health-records-service'

}

}

}

post {

always {

sh 'docker logout'

}

}

}